#!/bin/bash

###___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________ 
### 
### Program name:	SACRing.sh
### Function:		Sub-Assembly of Chloroplast genome from PE RAD-seq
### Citation:		Chao Feng, Meizhen Xu, Chen Feng, Eric J. B. von Wettberg, Ming Kang. The complete chloroplast genome of Primulina and two novel strategies for development of high polymorphic loci for phylogenetic studies. BMC Evolutionary Biology 2017;
### Author:		Chao Feng (chaofeng@scbg.ac.cn)
### Release date:	Jul. 14th, 2017
### Version:		Version 1.1
### Software:		This program is deponded on the following softwares, bowtie ("http://bowtie-bio.sourceforge.net/index.shtml"), bowtie2 ("http://bowtie-bio.sourceforge.net/bowtie2/index.shtml"), Stacks ("http://catchenlab.life.illinois.edu/stacks"), CAP3 ("http://seq.cs.iastate.edu/cap3.html") and blat ("https://users.soe.ucsc.edu/~kent/src"). Please make sure they have been installed and avaliable in your directory.
### Preparation:	1. Put a single reference chloroplast genome (fa format) in the folder of RefFile.
###			2. Put all the PE-end RAD-Seq (fq format) in the folder of FastqFile. Read1 (next to restriction site) should be named as $sample_1.fq, the other one as $sample_2.fq, e.g.: CZYX01-2_1.fq, CZYX01-2_2.fq.
### Usage:		nohup sh SACRing.sh $Ref $3'cohesive_end $Overlap_of_paired_tags $Read1_len $Read2_len $ThreadNumber >$Log 2>&1 &
###				$Ref: File of Reference cp genome, including the path, e.g. RefFile/WHY01.fa.
###				$3'cohesive_end: 3'end of restriction enzyme used in RAD-Seq, e.g. EcoR I (G'AATTC) was used in RAD-Seq, here print AATTC.
###				$Overlap_of_paired_tags: It was counted as following formula: the length of restriction enzyme - (Enzyme cutting position) x 2, e.g. EcoR I (G'AATTC) was used in RAD-Seq, here print 4 (6 - 1 x 2 = 4).
###				$Read1_len: the length of read1 in fastq file, e.g. 100.
###				$Read2_len: the length of read2 in fastq file, e.g. 100.
###				$ThreadNumber: Max Thread can be used in this analysis.
###				$Log: Record of output on the screen.
###			E.g.: nohup sh SACRing.sh RefFile/WHY01.fa AATTC 4 100 100 20 >Log.txt 2>&1 &
###	 Note:		Make sure that only three folders (RefFile, FastqFile and PerlScript) and three files (SACRing.sh, ReadMe, Pipeline.pdf) are existed in your work folder. Only the fq files which need to be analyzed exist in the folder of FastqFile, and only a fa file in RefFile.
###			There are an example of Ref and fq files in the corresponding folders to test whether the software required are prepared, and this pipeline is OK for your Linux system. Please delete the example files before running of your own data.
###			The fastq files with different length of read1/read2 pairs should be analyzed respectively. And all the read1 or read2 in a fastq file used in this pipeline should have uniform length.
###	 Output description:	RefFile
###				RegionBoundary: the length and sequences of the regions of LSC, IRb, SSC and IRa.
###				Cp_complete.fa: the sequence of ref cp genome with a new uniform name.
###				Cp_nr.fa: the sequence of the regions of LSC, IRb and SSC, excluding the IRa region.
###			FastqFile
###				Fq.list: list of the samples used in this analysis.
###			RAD_cp
###				Each sample would generate 2 fq files (*.cp_1.fq; *.cp_2.fq), which are the deep sequencing data related to cp genome.
###			RAD_tag
###				Each sample would generate 2 fa files (*.tag1.fa; *.tag2.fa).
###				*.tag1.fa: the fa file of tag1 sequences, which are clustered from read1s. Two paired tag1s were merged in to one sequences.
###					The id of fa files, e.g. >tag1.49789.P_234_235, >tag1.6923.-_302, >tag1.54565.+_250.
###						The 1st part: uniform ">tag1".
###						The 2nd part: the site of enzyme cutting position of tag1s, e.g. 49789, 6923, 54565.
###						The 3rd part: "P", "-" and "+" represent the tags are paired, single and mapped to the negative strand, single and mapped to positive strand, respectively.
###						The 4th part: the id of tag1s generated by the software of Stacks, e.g. 234, 235, 302 and 250.
###				*.tag2.fa: the fa of tag2 sequences. Based on PE relationship, the read2s with same tag1 cluster are extracted and further assembled.
###					The id of fa files, e.g. >tag2_115, >tag2_116. 115, 116 are the id of tag2, same to its corresponding tag1 id generated by the software of Stacks.
###			RAD_assembly
###				Each sample would generate 5 files (*.RAD_poTs, *.RAD_poTs.Stat, *.RAD_CpContigs, *.RAD_CpContigs.Stat, *.RAD_sub-super-marker).
###				*.RAD_poTs: The sequences of contigs assembled from Tag1s (clustered from read1 of RAD-Seq) at forward and reverse directions of the same restriction enzyme site and their corresponding Tag2s (assembled from read2s of RAD-Seq).
###					The id of fa (>), e.g. 100735P__CZYX01-1, 105533P__CZYX01-1. 100735 and 105533 indicate that the site of Enzyme cutting position of paired tag1; P is short for Paired; CZYX01-1 is the sample ID.
###				*.RAD_poTs.Stat: The information of each sequence in RAD_Tags. e.g. "3388	4672	4053P__CZYX01-1	1284"; "12765	14118	13442P__CZYX01-1	1353".
###					The 1st column: the start position of the poTs mapped to reference, e.g., 3388, 12765.
###					The 2nd column: the end position of the poTs mapped to reference, e.g., 4672, 14118.
###					The 3rd column: the id of the poTs, same to the id of RAD_Tag, e.g., 4053P__CZYX01-1, 13442P__CZYX01-1.
###					The 4th column: the length of the poTs, e.g., 1284, 1353.
###				*.RAD_CpContigs: The assembly configs from RAD cp data.
###					The id of fa (>), e.g., CpContig_1__CZYX01-11, CpContig_2__CZYX01-11. CZYX01-11 is the sample ID.
###				*.RAD_CpContigs.Stat: The information of longer sequences without unknown nucleotides, which was assembled from all the kinds of tags, according to their position and overlap information, e.g., "3388	4786	CpContig_1__CZYX01-1	1398"; "6446	6927	CpContig_2__CZYX01-1	481".
###					The 1st column: the start position of the CpContigs mapped to reference, e.g., 3388, 6446.
###					The 2nd column: the end position of the CpContigs mapped to reference, e.g., 4786, 6927.
###					The 3rd column: the id of the CpContigs, e.g., CpContig_1__CZYX01-11, CpContig_2__CZYX01-11.
###					The 4th column: the length of the CpContig, e.g., 1398, 481.
###				*.RAD_sub-super-marker: The assembly scaffold from RAD cp data. The gaps between two adjacent sequences in RAD_Asmb were filled with "-", and further assembled into only one scaffold.
###___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
###

Ref=$1;
RE=$2;
OPT=$3
Read1Len=$4;
Read2Len=$5;
Cpu=$6;

###########################
##Step1. Data Preparation##
###########################
 
perl PerlScript/Step1.1-RefRegionBoundary.pl $Ref
bowtie2-build RefFile/Cp_complete.fa RefFile/Cp_complete
bowtie-build RefFile/Cp_nr.fa RefFile/Cp_nr

cd FastqFile
find -name "*.fq" |sed 's/_[1-2].fq//'|sort -n |uniq >Fq.list
files=`cat Fq.list`
cd ..

#################################
##Step2. Chloroplast Extraction##
#################################

rm -rf RAD_cp
mkdir RAD_cp

i=1
for file in $files
do
	bowtie2 -x RefFile/Cp_complete -1 FastqFile/${file}_1.fq -2 FastqFile/${file}_2.fq -S RAD_cp/${file}.bowtie2.sam -I 150 -X 1000 --no-mixed --no-discordant -p $Cpu	## parameter of bowtie2, you can adjust as you wish, but do not change the name, format and path of the outputfile.
	bowtie --best RefFile/Cp_nr FastqFile/${file}_1.fq RAD_cp/${file}_1.bowtie -p $Cpu
	bowtie --best RefFile/Cp_nr FastqFile/${file}_2.fq RAD_cp/${file}_2.bowtie -p $Cpu
	perl PerlScript/Step2.1-BowtieExtract.pl ${file} $RE
	bowtie --best RefFile/Cp_nr RAD_cp/${file}_cp_1.fq RAD_cp/${file}_cp.bowtie -p $Cpu
	pstacks -m 100 -t bowtie -f RAD_cp/${file}_cp.bowtie -o RAD_cp -i $i -p $Cpu
	perl PerlScript/Step2.2-StacksExtract.pl ${file}
	rm -rf RAD_cp/*bowtie*
	rm -rf RAD_cp/*snps*
	rm -rf RAD_cp/*alleles*
	rm -rf RAD_cp/${file}_cp_1.fq
	let "i+=1";
done

rm -rf RefFile/*.bt2
rm -rf RefFile/*.ebwt

#########################
##Step3. Tag Extraction##
#########################

rm -rf RAD_tag
mkdir RAD_tag

for file in $files
do
	perl PerlScript/Step3.1-Tag1Extract.pl ${file} $OPT $Read1Len
done

mkdir RAD_tag/1Split
mkdir RAD_tag/2Id
mkdir RAD_tag/3Seq

for file in $files
do
	mkdir RAD_tag/1Split/${file}
	mkdir RAD_tag/2Id/${file}
	mkdir RAD_tag/3Seq/${file}
done

cd RAD_tag

for file in $files
do
	cd 1Split/${file}
	cp ../../../RAD_cp/${file}_cp.tags.tsv ./ 
	awk '{print > $3}' ${file}_cp.tags.tsv
	rm -rf version
	rm -rf ${file}_cp.tags.tsv
	cd ../..
done

for file in $files
do
	file1list=`ls 1Split/${file}`
	for file1 in $file1list
	do
		awk '{print $6}' 1Split/${file}/${file1} >2Id/${file}/${file1}
	done
done

cd 2Id
for file in $files
do
	ls ${file}/* | xargs -I {} -P $Cpu perl ../../PerlScript/Step3.2-Read2Extract.pl ../../RAD_cp/${file}.cp_2.fq {} ../3Seq/{}
done

cd ../3Seq
for file in $files
do
	ls ${file}/* | xargs -I {} -P $Cpu cap3 {}
done

for file in $files
do
	rm -rf ${file}/?
	rm -rf ${file}/??
	rm -rf ${file}/???
	rm -rf ${file}/*.cap.ace
	rm -rf ${file}/*.cap.info
	rm -rf ${file}/*.cap.contigs.links
	rm -rf ${file}/*.cap.contigs.qual
	rm -rf ${file}/*.singlets
	cd ${file}
	ls * | xargs -I {} -P $Cpu perl ../../../PerlScript/Step3.3-LongestCAP3.pl {}
	find -name "*.cap.contigs.Longest" -exec 'cat' {} \; >../${file}.read2.fa
	cd ..
	blat ../../RefFile/Cp_nr.fa ${file}.read2.fa ${file}.read2.psl
	perl ../../PerlScript/Step3.4-Tag2Extract.pl ${file}.read2.fa ${file}.read2.psl ../${file}.tag2.fa $Read1Len $Read2Len
done

cd ../..

###################
##Step4. Assembly##
###################

rm -rf RAD_assembly
mkdir RAD_assembly
for file in $files
do
	perl -nle "print" RAD_tag/${file}.tag1.fa RAD_tag/${file}.tag2.fa >RAD_assembly/${file}.tagC.fa
	blat RefFile/Cp_nr.fa RAD_assembly/${file}.tagC.fa RAD_assembly/${file}.tagC.psl
	perl PerlScript/Step4.1-TagCPslExtract.pl RAD_assembly/${file}.tagC.psl RAD_assembly/${file}.tagC.pos.txt $Read1Len $Read2Len
	sort -n RAD_assembly/${file}.tagC.pos.txt >RAD_assembly/${file}.tagC.sort.txt
	perl PerlScript/Step4.2-TagCAssembly.pl RAD_assembly/${file}.tagC.fa RAD_assembly/${file}.tagC.sort.txt RAD_assembly/${file}.tagC.sort RAD_assembly/${file}.RAD_poTs ${file}
	blat RefFile/Cp_nr.fa RAD_assembly/${file}.RAD_poTs RAD_assembly/${file}.RAD_poTs.psl
	perl PerlScript/Step4.3-PslExtract.pl RAD_assembly/${file}.RAD_poTs.psl RAD_assembly/${file}.RAD_poTs.pos.txt $Read1Len $Read2Len
	sort -n RAD_assembly/${file}.RAD_poTs.pos.txt >RAD_assembly/${file}.RAD_poTs.Stat
	perl -nle "print" RAD_assembly/${file}.tagC.sort.C RAD_assembly/${file}.tagC.sort.S >RAD_assembly/${file}.tagC.sort
	cap3 RAD_assembly/${file}.tagC.sort
	perl -nle "print" RAD_assembly/${file}.tagC.sort.cap.contigs RAD_assembly/${file}.tagC.sort.cap.singlets >RAD_assembly/${file}.tagC2.fa
	blat RefFile/Cp_nr.fa RAD_assembly/${file}.tagC2.fa RAD_assembly/${file}.tagC2.psl
	perl PerlScript/Step4.3-PslExtract.pl RAD_assembly/${file}.tagC2.psl RAD_assembly/${file}.tagC2.pos.txt $Read1Len $Read2Len
	sort -n RAD_assembly/${file}.tagC2.pos.txt >RAD_assembly/${file}.tagC2.sort.txt
	perl PerlScript/Step4.4-TagCAssembly.pl RAD_assembly/${file}.tagC2.fa RAD_assembly/${file}.tagC2.sort.txt RAD_assembly/${file}.tagC3.fa
	blat RefFile/Cp_nr.fa RAD_assembly/${file}.tagC3.fa RAD_assembly/${file}.tagC3.psl
	perl PerlScript/Step4.3-PslExtract.pl RAD_assembly/${file}.tagC3.psl RAD_assembly/${file}.tagC3.pos.txt $Read1Len $Read2Len
	sort -n RAD_assembly/${file}.tagC3.pos.txt >RAD_assembly/${file}.tagC3.sort.txt
	perl PerlScript/Step4.5-FinalAssembly.pl RAD_assembly/${file}.tagC3.fa RAD_assembly/${file}.tagC3.sort.txt RAD_assembly/${file}.RAD_CpContigs RAD_assembly/${file}.RAD_sub-super-marker ${file}
done

rm -rf RAD_assembly/*.psl
rm -rf RAD_assembly/*.tmp
rm -rf RAD_assembly/*pos.txt
rm -rf RAD_assembly/*tagC*fa
rm -rf RAD_assembly/*tagC?.sort.txt
rm -rf RAD_assembly/*.tagC.sort*
rm -rf RAD_cp/*.tsv
rm -rf RAD_tag/1Split
rm -rf RAD_tag/2Id
rm -rf RAD_tag/3Seq
rm -rf RAD_tag/*.RAD.tags

